version: "3"
services:
    web:
        image: php:7.2-apache
        container_name: "app"
        volumes:
            - $PWD:/var/www/html
        ports: 
            - "8081:80"
    #    links: 
    #        - "db:app.db"
    #db:
    #    image: mysql:5.7
    #    container_name: "app.db"
    #    ports:
    #        - "3306:3306"
    #    environment:
    #        MYSQL_ROOT_PASSWORD: root
    #        MYSQL_DATABASE: lamp_db
    #        MYSQL_USER: lamp_user
    #        MYSQL_PASSWORD: lamp_pw