version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:7.2-apache
        container_name: "app"
        volumes:
            - ./:/var/www/html/
        ports: 
            - "8083:80"
        links: 
            - "db:app.db"
    db:
        image: mysql:5.7
        container_name: "app.db"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mysql_db
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_pw